### ISSUE TITLE
Getting error - pgaudit.c:738: error: ‘LOG_SERVER_ONLY’ undeclared

### ISSUE THREAD

**Issue by rishmax** [pgaudit/pgaudit#29]
Hi Team,

I am getting error while executing following command:
Command:
make USE_PGXS=1

Error:
pgaudit.c: In function ‘log_audit_event’:
pgaudit.c:738: error: ‘LOG_SERVER_ONLY’ undeclared (first use in this function)
pgaudit.c:738: error: (Each undeclared identifier is reported only once
pgaudit.c:738: error: for each function it appears in.)

We are running PostgreSQL 9.5.3 and we installed it using source code
I am in process of evaluating pgAudit extension. 

I really appreciate any help here.

Thanks:
Rishabh

**Comment by dwsteele** [comment]
The version in master (1.1.X) will only build on 9.6.  You'll want to get the 1.05 release for 9.5:

https://github.com/pgaudit/pgaudit/blob/master/README.md#postgresql-version-compatibility

**Comment by rishmax** [comment]
Thank you so much for your quick help.
I installed 1.0.5 and now it is working for me.
